#!/bin/sh

# /etc/X11/xinit/xinitrc
#
# global xinitrc file, used by all X sessions started by xinit (startx)

# invoke global X session script

cd /home/pi/Curing_Machine
git stash
git pull
cd /home/pi/Curing_Machine/Code
sudo chmod +x curingMachine.py
sudo python3 curingMachine.py
# invoke global X session script


. /etc/X11/Xsession
